# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - first-py-app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  front-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Store variables
        run: |
          cd front-app
          touch .env
          echo "REACT_APP_DEV_SERVER_URL=${{ secrets.DEV_SERVER_URL }}" >> .env

          echo "lets try quotes"
          echo 'REACT_APP_A=${{ secrets.DEV_SERVER_URL }}' >> .env_quotes
          cat .env_quotes
          echo "==="
          echo "lets try double quotes"
          echo "REACT_APP_A=${{ secrets.DEV_SERVER_URL }}" >> .env_double_quotes
          cat .env_double_quotes
          echo "==="
          echo "lets try plaintext"
          echo "REACT_APP_A='https://first-py-app.azurewebsites.net/'" >> .env_plaintext
          cat .env_plaintext

      - name: Build
        run: |
          cd front-app
          npm install
          npm run-script build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_DEV_NIKONOV91_TOKEN }}
          BRANCH: gh-pages
          FOLDER: 'front-app/build'

#  back-build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@master
#
#      - name: Set up Python version
#        uses: actions/setup-python@v1
#        with:
#          python-version: '3.8'
#
#      - name: Build using AppService-Build
#        uses: azure/appservice-build@v2
#        with:
#          platform: python
#          platform-version: '3.8'
#
#      - name: 'Deploy to Azure Web App'
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: 'first-py-app'
#          slot-name: 'production'
#          publish-profile: ${{ secrets.AzureAppService_PublishProfile_7edcdecca83a4354a87943f94bb32fca }}